apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pitsa.fullname" . }}-enprov
  labels:
    {{- include "pitsa.labels" . | nindent 4 }}
type: Opaque
data:
  enprov.json: {{ .Values.app.signature.enprov | toJson | b64enc }}
